---
title: "Bio"
---

```{js, echo=FALSE}  
(function() {  
  for (const link of document.getElementsByTagName('a')) {  
    if (/^(https?:)?\/\//.test(link.getAttribute('href'))) link.target = '_blank';  
  }  
})();  
``` 

I am a professor of biostatistics at the [Oslo Centre of Biostatistics and Epidemiology](https://www.med.uio.no/imb/english/research/centres/ocbe/){target="_blank"}, Department of Biostatistics, University of Oslo, working on causal inference and time-to-event analysis.

I have a PhD in biostatistics from the University of Oslo in 2011 and a MSc in Industrial Mathematics from the Norwegian University of Science and Technology in Trondheim in 2005. I have previously also had positions at the Section for Biostatistics and Epidemiology at the Oslo University Hospital, and at the Department of Infectious Disease Epidemiology at the Norwegian Institute of Public Health. 

I am an associate editor in [Biometrika](https://academic.oup.com/biomet){target="_blank"}.

See also my [web pages at the University of Oslo](https://www.med.uio.no/imb/english/people/aca/jonmic/index.html){target="_blank"} and the web pages of the [causal inference and survival analysis group](https://www.med.uio.no/imb/english/research/groups/causal-inference-methods/index.html){target="_blank"}.