---
title: "Research"
format: html
css: styles.css
about:
  template: jolla
---

<center>

My main research interests are causal inference and time-to-event analysis. In particular, I am interested in problems related to estimating the effects of time-varying treatments, time-dependent confounding and other sources of bias in longitudinal settings, time-to-event data, competing risk and multi-state modelling of more complex individual event histories. I also have an interest in studies of infectious diseases and the added complexities when studying treatment effects in such settings, and I have done some work on excess mortality estimation, infectious disease surveillance and infectious disease modelling.

I am interested in applications using both randomised and observational data, and in particular event history data constructed from linked clinical and population-wide registries. I am currently involved in various collaborative projects, e.g. on the effects of rehabilitation and pain medication on patient outcomes after traumatic injury with researchers at [the Oslo University Hospital](https://www.ous-research.no/ipot/){target="_blank"}, and on the effects of rehabilitation and workplace initiatives on long-term sick leave and work-related outcomes with researchers at [the National Institute of Occupational Health in Norway](https://stami.no/en/){target="_blank"}. I am currently the PI of such projects with funding from the Research Council of Norway and the Institute of Basic Medical Sciences, University of Oslo. Through my work at [the Norwegian Institute of Public Health](https://www.fhi.no/en/){target="_blank"} I'm involved in projects on the estimation of vaccine effects from observational data.

See my [Google Scholar profile](https://scholar.google.no/citations?hl=en&pli=1&user=GRG21B8AAAAJ){target="_blank"} for publications.
