---
title: "Research"
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

```{js, echo=FALSE}  
(function() {  
  for (const link of document.getElementsByTagName('a')) {  
    if (/^(https?:)?\/\//.test(link.getAttribute('href'))) link.target = '_blank';  
  }  
})();  
``` 

My main research interests are [causal inference and time-to-event analysis](https://www.med.uio.no/imb/english/research/groups/causal-inference-methods/index.html){target="_blank"}. In particular, I have worked on methods for estimating the effects of time-varying treatments on survival outcomes under time-dependent confounding and multi-state modelling of event history data. I also have an interest, and have done some work, in studies of infectious diseases, such as excess mortality, infectious disease surveillance and infectious disease modelling.

I am interested in applications to both randomised and observational data, including linked clinical and population wide registries. I am currently involved in various collaborative projects, e.g. on the effects of drug use on patient outcomes after traumatic injury with researchers at [the Oslo University Hospital](https://www.ous-research.no/ipot/){target="_blank"}, funded by the Institute of Basic Medical Sciences, University of Oslo, and on the effects of workplace initiatives on sick leave and work-related outcomes with researchers at [the National Institute of Occupational Health in Norway](https://stami.no/en/){target="_blank"}, funded by the Research Council of Norway.

See my [Google Scholar profile](https://scholar.google.no/citations?hl=en&pli=1&user=GRG21B8AAAAJ){target="_blank"} for a list of publications.